### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by dbeckwith** [matthiaskrgr/cargo-cache#10]
```
$ cargo --version
cargo 1.28.0 (96a2c7d16 2018-07-13)
$ cargo install --git https://github.com/matthiaskrgr/cargo-cache
    Updating git repository `https://github.com/matthiaskrgr/cargo-cache`
error: no packages found with binaries or examples
```

**Comment by matthiaskrgr** [comment]
Hi, I use a few features that are only available with ````rust 1.30````, could you try the nighty channel?
Perhaps ````cargo +nightly install --git https://github.com/matthiaskrgr/cargo-cache```` works?

**Comment by dbeckwith** [comment]
Ah, yep that did it. And I see now you do mention the version in the README. Maybe should update the command in the README to have the `+nightly`.

**Comment by matthiaskrgr** [comment]
Good idea, I'll fix that :)
