### ISSUE TITLE
cargo-cache requires libgit

### ISSUE THREAD

**Issue by thedrow** [matthiaskrgr/cargo-cache#103]
When I run `cargo cache --autoclean` I get the following error:
```
/home/thedrow/.cargo/bin/cargo-cache: error while loading shared libraries: libgit2.so.1.1: cannot open shared object file: No such file or directory
```

This is not documented anywhere.
I'd prefer to have libgit2 bundled as a static library in this binary instead of installing it myself.

**Comment by matthiaskrgr** [comment]
Mmh, I'm not sure if libgit2-rs supports that.
I think cargo also depends on a static lib the same way.

Does simply reinstalling cargo-cache fix the problem?

**Comment by thedrow** [comment]
Unfortunately no. I had to install the library from apt to ensure the extension works.

**Comment by matthiaskrgr** [comment]
But you could use regular "cargo" commands (like cargo build, cargo fetch or cargo update) before and that worked fine? Hm..

**Comment by thedrow** [comment]
Yes, I could.

**Comment by matthiaskrgr** [comment]
Fixed by @afnanenayet in https://github.com/matthiaskrgr/cargo-cache/pull/105 :)
