### ISSUE TITLE
Cleaning target artefacts

### ISSUE THREAD

**Issue by installgentoo** [matthiaskrgr/cargo-cache#104]
Is it possible to cleanup target with this? Specifically clean out all the stuff from package versions that are not in lockfile.

If not the extension seems kinda pointless to me, because by the point your .cargo directory will take up maybe 500mb, your target will be at 3-8 GB. what's the point of cleaning up 200mb if you'll still have the bloated target? and if you just delete target you'd have to rebuild everything.

**Comment by pickfire** [comment]
I was looking for this too, maybe we can link cargo-sweep in the README?

**Comment by installgentoo** [comment]
> I was looking for this too, maybe we can link cargo-sweep in the README? And vice versa cc @holmgr, but cargo-sweep project seemed dead.

cargo-sweep is a useless 'effin program, that's literally equivalent to running find -delete

I am amazed to this day that no one though rust's build system should clean up after itself. Apparently disk space is infinite.

**Comment by holmgr** [comment]
> I was looking for this too, maybe we can link cargo-sweep in the README? And vice versa cc @holmgr, but cargo-sweep project seemed dead. Maybe it is even possible to integrate cargo-sweep into cargo-cache.

Hi that sounds pretty reasonable to me. However, I am no longer the primary maintainer, but @jyn514 is. I’ll let him decide
