### ISSUE TITLE
Move static git bundling to a (default) feature

### ISSUE THREAD

**Issue by bertptrs** [matthiaskrgr/cargo-cache#115]
Ever since 2497227090b9e68e4fa37b6da2c95bb1432d8600 this crate bundles libgit as a vendored dependency rather than relying on the system version of `libgit2`. This static linking can cause small issues ([as reported here](https://aur.archlinux.org/packages/cargo-cache/#comment-843713)) when combined with certain loader environments.

The vendoring was originally added to deal with similar but different issues. I think we can get the best of both worlds by moving the functionality to a crate feature: `vendored_git` or whatever colour you like your bike shed. We can then enable this feature by default, so that the normal experience is maintained, but people who want to use their system libs can do so with a more minimal install.

If you agree with going this direction, I could implement it. Let me know what you think.

**Comment by matthiaskrgr** [comment]
Mmh so we would have a separate feature like 
```toml
[features]
vendored-libgit = ["git2/vendored-libgit2"]
```
which turns on the libgit2 vendoring and it would be added to the default feature, so that the default does not change and in order to build with unvendored libgit2, we build with `--no-default-features`?

This will probably fail because of https://github.com/matthiaskrgr/cargo-cache/issues/106 :( 

I'm not sure if there is an easy way to turn of only a single default-feature like `--features !foo`

**Comment by matthiaskrgr** [comment]
from the aur pkgbuild logs:
````
upstream release. Also disable upstream's vendoring of libgit2 as Arch
ships a recent enough version not to need it.
````
I'm a bit curious about the idea behind "ships a recent enough version not to need it".
I have `cargo-cache` installed via rust/`cargo install` and whenever I would do a bigger system update, `cargo-cache` would need to be rebuild against the updated system libgit which is annoying.
Is there a better workaround for this?

**Comment by matthiaskrgr** [comment]
Something like this might work:
````patch
diff --git a/Cargo.toml b/Cargo.toml
index c6e324f..928efb0 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -15,9 +15,10 @@ resolver = "2"
 rust-version = "1.56"

 [features]
-default = ["cargo_metadata", "chrono", "clap", "dirs-next", "git2", "humansize", "rayon", "regex", "rustc_tools_util", "walkdir", "tar", "flate2"]
+default = ["cargo_metadata", "chrono", "clap", "dirs-next", "git2", "humansize", "rayon", "regex", "rustc_tools_util", "walkdir", "tar", "flate2", "vendore>
 bench = [] # run benchmarks
 ci-autoclean = [] # minimal implementation that builds fast for CI
+vendored-libgit = ["git2/vendored-libgit2"]
 offline_tests =  [] # only run tests that do not require internet connection
 # some details: https://github.com/NixOS/nixpkgs/pull/77310
 [dependencies]
 diff --git a/README.md b/README.md
index d365c95..1b3a4ed 100644
--- a/README.md
+++ b/README.md
@@ -166,7 +166,7 @@ To reduce the size of the cache before storing it, you might want to run `cargo
 The `ci-autoclean` feature provides a very stripped-down version of the crate that is only capable of running `cargo-cache --autoclean` automatically on la>
 To make use of this, you can add these commands to your ci:
 ````bash
-cargo install (--git git://github.com/matthiaskrgr/cargo-cache OR cargo-cache) --no-default-features --features ci-autoclean cargo-cache
+cargo install (--git git://github.com/matthiaskrgr/cargo-cache OR cargo-cache) --no-default-features --features ci-autoclean cargo-cache vendored-libgit
 cargo-cache # no further arguments required
 ````

 ````

**Comment by bertptrs** [comment]
First of all, thank you for looking into this.

I think that would be perfect. A potential future improvement would be to disable vendored libgit2 for `ci-autoclean` as well, but as it stands libgit2 compiles fast enough not for this to matter.

**Comment by matthiaskrgr** [comment]
I think by "default" (if you just do `cargo install cargo-cache --no-default-features --features ci-autoclean cargo-cache`) that should even link libgit2 dynamically since `--no-default-features` disables the `vendored-libgit` feature. :)

**Comment by matthiaskrgr** [comment]
Merged into master via https://github.com/matthiaskrgr/cargo-cache/commit/682485af223109668e9ee78f9cd20f01bb483e5b
Let me know if there is anything else that you need :)

**Comment by bertptrs** [comment]
Thanks. I'll update the package once this ends up in a tagged release. No rush for that of course, this is hardly deserving of a bump.
