### ISSUE TITLE
 cargo cache -a on a arm procesor

### ISSUE THREAD

**Issue by Totobal5** [matthiaskrgr/cargo-cache#117]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { depth: 2, inner: Io { path: None, err: Os { code: 5, kind: Uncategorized, message: "Input/output error" } } }', /mnt/linarchivos/plume/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-cache-0.8.1/src/cache/registry_sources.rs:90:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Trying to clear the cache on a very basic device and with the address of $CARGO_HOME changed to an external drive

**Comment by Totobal5** [comment]
Sorry for the delay in replying
The error was on my part as my hard drive had become corrupted, once a formatting was done everything went back to normal.

**Comment by matthiaskrgr** [comment]
Ouch that sounds bad. But thanks for the followup!
