### ISSUE TITLE
cachepot support

### ISSUE THREAD

**Issue by rbtcollins** [matthiaskrgr/cargo-cache#124]
https://github.com/paritytech/cachepot is a fork of sccache that is getting some traction. Perhaps add support for it's default local cache, like the sccache support you already have?

**Comment by matthiaskrgr** [comment]
Should be easy, only need to read another envvar/dir and print stats.

Just need to decide whether it makes most sense to add the additional infos to the sccache/sc subcommand or add a new subcommand.

**Comment by rbtcollins** [comment]
Or possibly don't bother - the cachepot folk say their changes are being merged into sccache incrementally https://github.com/paritytech/cachepot/issues/169
