### ISSUE TITLE
Odd wording

### ISSUE THREAD

**Issue by exoosh** [matthiaskrgr/cargo-cache#126]
Hi, when attempting certain operations I saw a message such as:

> Failed to Cargo.toml manifest in C:\ or downwards.

I think there's a "find" missing in that sentence.

It's cosmetic, of course. Thanks for this brilliant little tool.

**Comment by matthiaskrgr** [comment]
Oops, thanks, sometimes words are hard :rofl: 

Pushed a fix, will be rolled out with the next release, whenever that will be :upside_down_face:
