### ISSUE TITLE
Date doesn't seem validated

### ISSUE THREAD

**Issue by DuckDuckWhale** [matthiaskrgr/cargo-cache#127]
Using `--remove-if-older-than '1 year'` caused everything to be removed.

**Comment by matthiaskrgr** [comment]
Hm, looks like I had a bug in the config parsing...
So for `--remove-if...` you have to pass `--remove-dir` but then I read the config as if only `--remove-dir` is passed (without any date constraints) which will caused the entire directory to be removed. :/
