### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by flip111** [matthiaskrgr/cargo-cache#13]
Maybe this project is ready to be published on crates.io ?

**Comment by bemeurer** [comment]
@matthiaskrgr Feedback on this? I agree with @flip111.

**Comment by matthiaskrgr** [comment]
I'll try to make a first release around xmas!

Does anyone use windows and could give this a try?

**Comment by matthiaskrgr** [comment]
The crate is released on crates.io now. :tada:
Thanks for your patience!

https://crates.io/crates/cargo-cache
