### ISSUE TITLE
compile with stable

### ISSUE THREAD

**Issue by flip111** [matthiaskrgr/cargo-cache#14]
Please as soon as 1.30 becomes stable remove the requirement of nightly, because i like to use this package to reduce disk space and don't want to download another version of the compiler to do so.

**Comment by matthiaskrgr** [comment]
Hmm, it seems that the test feature isn't stable either.
I'll see if I can work around by moving all the tests into a subdir.

**Comment by matthiaskrgr** [comment]
Ok, turns out the test feature is only needed for benchmarks.
I hid all the benchmark related things behind a feature now to make sure the default build works.

**Comment by matthiaskrgr** [comment]
The next step is to update rustc_tools_util dependency where I removed the need for the test feature (which is not stabilized) and wait for tool_lints to be come stable, I guess?

**Comment by flip111** [comment]
Seems right, just to wait for the moment

**Comment by matthiaskrgr** [comment]
As of 584a774cad01e95f5ed1fe0c7ade42d2f44c95e3, it is possible to build with beta :)

**Comment by mitchtbaum** [comment]
1.30 has been released

**Comment by matthiaskrgr** [comment]
It seems that 1.30 got the stabilization of edition2018 reverted so we need to wait for 1.31 to be released :/
https://internals.rust-lang.org/t/rust-2018-release-schedule-and-extended-beta/8076
