### ISSUE TITLE
check if cargo-cache works on windows

### ISSUE THREAD

**Issue by matthiaskrgr** [matthiaskrgr/cargo-cache#22]
I have no idea if this works on windows and I don't have access to a windows machine with rust support.

Could someone using rust on windows give this a try and report back?
Any feedback is welcome! :)

**Comment by flip111** [comment]
what should be tested about this ?

**Comment by matthiaskrgr** [comment]
Make sure the output of
cargo cache
cargo cache --autoclean-expensive --dry-run
cargo cache --info
cargo cache --list-dirs
cargo cache -top-cache-items 10
looks ok (and there are no panics).

Maybe run tests (I assume this will fail since I have never done this before)

**Comment by idursun** [comment]
It does show the sizes alright but `autoclean` has failed with a permission problem. It fails also in the elevated mode (admin) as well. 

```
Total size:                             861.16 MB
Size of 21 installed binaries:            147.52 MB
Size of registry:                         668.09 MB
Size of 673 crate archives:                 66.05 MB
Size of 673 crate source checkouts:         398.16 MB
Size of git db:                           45.56 MB
Size of 4 bare git repos:                   20.85 MB
Size of 4 git repo checkouts:               24.71 MB
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', libcore\result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

back trace is not very useful but here it goes:

```
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: git_hashsig_create_fromfile
  10: BaseThreadInitThunk
  11: RtlUserThreadStart
```

**Comment by matthiaskrgr** [comment]
Err, I would not run this as admin.. :D
It's strange that there is no backtrace.
Is this a release build?

**Comment by idursun** [comment]
Yes, it was a release build.

I have recompiled with debug, but the backtrace is still similar

```
d:\repositories\rust\names>cargo cache -a
Cargo cache 'C:\Users\Ibrahim.Dursun\.cargo/':

Total size:                             232.35 MB
Size of 16 installed binaries:            147.96 MB
Size of registry:                         39.77 MB
Size of 129 crate archives:                 14.41 MB
Size of 0 crate source checkouts:           0 B
Size of git db:                           44.62 MB
Size of 3 bare git repos:                   19.92 MB
Size of 4 git repo checkouts:               24.70 MB
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', libcore\result.rs:1009:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: git_libgit2_opts
  18: BaseThreadInitThunk
  19: RtlUserThreadStart
```

**Comment by idursun** [comment]
@matthiaskrgr I have run the command with dry-run to see what directories would be removed and here is the output.

```
d:\repositories\rust\cargo-cache>cargo run --bin cargo-cache -- -a --dry-run
    Finished dev [unoptimized + debuginfo] target(s) in 0.85s
     Running `target\debug\cargo-cache.exe -a --dry-run`
Cargo cache 'C:\Users\Ibrahim.Dursun\.cargo/':

Total size:                             308.82 MB
Size of 16 installed binaries:            147.96 MB
Size of registry:                         116.24 MB
Size of 132 crate archives:                 14.64 MB
Size of 132 crate source checkouts:         76.24 MB
Size of git db:                           44.62 MB
Size of 3 bare git repos:                   19.92 MB
Size of 4 git repo checkouts:               24.70 MB
would remove directory 'C:\Users\Ibrahim.Dursun\.cargo\registry/src/'
would remove directory 'C:\Users\Ibrahim.Dursun\.cargo\git/checkouts/'
```

I think this is happening because of the mixed up back and forward slashes.

**Comment by matthiaskrgr** [comment]
Oooooh, that sounds plausible. I'll have a look

**Comment by idursun** [comment]
@matthiaskrgr 

Offending directory is the second one `C:\Users\Ibrahim.Dursun\.cargo\git/checkouts/` and back or forward slashes don't cause the problem.

If there are readonly files in the directory then the `fs::remove_all_dir` call panicks.

```rust
let pf = PathBuf::from("D:\\something\\");
let _ = fs::remove_dir_all(&pf).unwrap();
```

Create a readonly file inside the `something` folder to reproduce.

**Comment by matthiaskrgr** [comment]
It might be that git sets its internal files as read-only ( to prevent accidental deletion) and we are choking on those on windows...

**Comment by matthiaskrgr** [comment]
@idursun so the crash was happening in `--autoclean` when `fs::remove_dir::all()` failed to delete a directory.
For now I have added a small debug message that will pop up if that happens (it will still panic though).
https://github.com/matthiaskrgr/cargo-cache/commit/37836077258699aea6cfd0666e68c1f50e4e444e

**Comment by Eh2406** [comment]
I was pleasantly surprised to discover that cargo-sweep does the `print a warning on every file that could not be deleted`.

**Comment by matthiaskrgr** [comment]
Ok, we should now get a warning on every file that could not be deleted (I hope this is not too spammy) but continue execution if possible. :+1:

**Comment by matthiaskrgr** [comment]
The inconsistent paths should be fixed with 682fbe4117da3a3a153f71e8d9b654ddc74f6473

**Comment by idursun** [comment]
@matthiaskrgr I think it is the most reasonable thing to do at the moment. Thanks for the fix.

**Comment by matthiaskrgr** [comment]
Please let me know if there's anything else that seems odd! :)

**Comment by matthiaskrgr** [comment]
Thanks again everyone!
Tests pass on windows now, and I have enabled travis ci windows jobs to make sure future breakage is noticed.

If you find something odd, please open a ticket. :)
