### ISSUE TITLE
build failure of cargo dependency

### ISSUE THREAD

**Issue by iwconfig** [matthiaskrgr/cargo-cache#34]
I've tried both stable and nightly channel but it keeps on failing to compile. I've tried both the crate release and the latest from git but the same error message appears.

    error: failed to compile `cargo-cache v0.1.2 (https://github.com/matthiaskrgr/cargo-cache#7b808792)`, intermediate artifacts can be found at `/tmp/cargo-install3Mt63g`

I'm not that familiar with rust so I don't really know what's happening here.

**Comment by matthiaskrgr** [comment]
Hmm, the error message is very helping... :/
Is there any more error output when it fails to build?
What command did you try to compile it?

**Comment by iwconfig** [comment]
Yes sorry, of course. It seems to fail when compiling `Cargo` v0.34.0.

Compilation output: [https://hastebin.com/xebozihoga.txt](https://hastebin.com/xebozihoga.txt)

**Comment by matthiaskrgr** [comment]
Ah, to build the cargo dependency, you may need to install a `libssl-dev` package or something similar.
https://github.com/rust-lang/cargo#compiling-from-source

**Comment by iwconfig** [comment]
I already have `libssl-dev` package installed. I use Debian which also has `libssl1.1` and `libssl1.0-dev` available. I tried compiling with those packages installed but to no avail. Instead I get this error: https://hastebin.com/jovofuxuza.txt

I guess it has something to do with `libcurl`, which I also already have installed.

    $ apt list --installed | grep libcurl
    libcurl3/stable,stable,now 7.52.1-5+deb9u9 amd64 [installed,automatic]
    libcurl3-dbg/stable,stable,now 7.52.1-5+deb9u9 amd64 [installed]
    libcurl3-gnutls/stable,stable,now 7.52.1-5+deb9u9 amd64 [installed,automatic]

I also tried to compile with `libcurl4-openssl-dev` package installed but the error remained the same.

I have ...

* `git`
* `python`
* `curl`
* `libssl-dev` and later `libssl1.0-dev`
* `cargo` and `rustc` ofc

already installed.

**Comment by matthiaskrgr** [comment]
>Instead I get this error: 

This looks already better imo because there are a lot less errors :smile: 

Is there perhaps some curl/libcurl dev package you can install? Perhaps `libcurl4-gnutls-dev` makes it work?

**Comment by iwconfig** [comment]
Haha yeah that is true. :) 

Yes, I forgot to mention that one. I've tried both

* `libcurl4-gnutls-dev`
* `libcurl4-nss-dev` and
* `libcurl4-openssl-dev`,

but the same error appeared each time. Here's a verbose output: https://hastebin.com/jizeyewaxi.txt
I trimmed it down to the interesting part

**Comment by matthiaskrgr** [comment]
Ok, just to be sure, could you please clone this repo https://github.com/rust-lang/cargo and run cargo build / cargo build --release and see if you get the same linking error?

**Comment by iwconfig** [comment]
Jeez, I clearly wasn't focused yesterday, I'm sorry. That was the first thing I tried and I get the same error. Same error as when compiling `cargo-cache` both before and after I installed `libssl1.0-dev`. So I guess the problem lies within compilation of `cargo` and not really `cargo-cache` itself.

If it's of any help, here's a verbose output of `cargo build --release`: https://hastebin.com/raw/bupimoxumi

I'll do further research. In the meantime, I'll keep this issue open.

**Comment by matthiaskrgr** [comment]
I asked in the cargo channel on discord if someone has seen your error before:
>I haven't seen that error before. Looking at the output, it looks like libcurl is being built statically, so looking at which libcurl is installed is probably a distraction. To debug these, I would run with cargo build -vv to get all the build script output to see which settings are being used for [curl-sys] and [openssl-sys]. For example, on my system, OPENSSL_NO_SSL3_METHOD is set in /usr/include/x86_64-linux-gnu/openssl/opensslconf.h which libcurl detects and excludes SSLv3_client_method from being used. It seems like the header files are out of sync with the libssl.so maybe?

**Comment by matthiaskrgr** [comment]
I got rid of the cargo dependency in https://github.com/matthiaskrgr/cargo-cache/commit/38b247b0bdc7c73a68059b94c68896e1f2097aa4#diff-80398c5faae3c069e4e6aa2ed11b28c0
which is also featured in version 0.2.0.
I think this issue should be resolved with this.
