### ISSUE TITLE
Support for cleaning out cached crates not referenced in a Cargo.lock

### ISSUE THREAD

**Issue by mathstuf** [matthiaskrgr/cargo-cache#76]
For CI purposes, I have the builders keep a cache of crates downloaded so that the build and test steps can be run with `--frozen --offline` and ensure that all builders are using the same dependency sets. It'd be nice if, after I run `cargo generate-lockfile && cargo fetch`, I could run `cargo cache clean --unused` so that cached crates are not taking up cache (and artifact) space.

**Comment by mzabaluev** [comment]
This is what I was searching for when I found this crate.

Caches in CI are typically managed per project and used in a build environment assembled for each individual project build. For cloud-hosted CI platforms especially, the cache size has an impact on build time and possibly on resource budget, so in many setups it makes sense to keep the cargo cache minimally lean to satisfy a particular state of `Cargo.lock`, which can then be checksummed for a hierarchical caching key scheme.

**Comment by matthiaskrgr** [comment]
Just to make sure I understood correctly, you want `cargo-cache` to be able to remove all items in the `${CARGO_HOME}` that are not referenced in the `Cargo.lock` of a project, right?

**Comment by mathstuf** [comment]
Yes, that sounds like the behavior I'd want. I suspect the docs for it should note that it is intended for usage by CI systems (a user could do it too, but anyone working on more than one workspace would likely lose on lots of cache hits).

**Comment by matthiaskrgr** [comment]
So, I think I can use cargo-metadata (which is already a dependency!) to generate a list of packages referenced in the Cargo.toml and check if they exist in the cache.
This does not sound too difficult (famous last words lol).

**Comment by matthiaskrgr** [comment]
So, I still need to do more testing and clean this up a bit but I think the feature mostly works now:
https://github.com/matthiaskrgr/cargo-cache/tree/clear_unref (the `clear_unref` branch).

If you `cd` into a repo you can run `../path/to/cargo-cache --clear-unref (--dry-run)` to remove crate archives of crates that are not referenced in the Cargo.toml of the project inside the current directory from the cache. :tada:

I wonder if it would be better to have some kind of --path argument so one does not have to cd into the project dir first, what do you think?

**Comment by mathstuf** [comment]
> I wonder if it would be better to have some kind of --path argument so one does not have to cd into the project dir first, what do you think?

Other `cargo` subcommands usually spell it `--manifest-path`. But I think to argument would make sense.

**Comment by matthiaskrgr** [comment]
I made it a subcommand now, so `cargo cache clean-unref --manifest-path=path/to&Cargo.toml` should work. :)

**Comment by matthiaskrgr** [comment]
The feature is in the master branch now, if you have any issues, please let me know! :)
