### ISSUE TITLE
Tag 0.3.4 release

### ISSUE THREAD

**Issue by yegortimoshenko** [matthiaskrgr/cargo-cache#79]
Judging by https://crates.io/crates/cargo-cache, 0.3.4 was released but corresponding git tag was not cut. Could you tag the commit that was used for crates.io release? :)

**Comment by matthiaskrgr** [comment]
Oh woops, thanks!
I actually had it in my repo but it looks like I forgot to push it online...

The commit should be 650849a36e232965741869e8007aa8780d4b1bd9
Link to the tag: https://github.com/matthiaskrgr/cargo-cache/tree/0.3.4
