### ISSUE TITLE
Need a hand?

### ISSUE THREAD

**Issue by gabo01** [matthiaskrgr/cargo-cache#8]
Hi, do you have any idea when you will a have a first release of this crate? This is a nice functionality to have since cargo does not support it natively and I'm sure many would appreciate it. I would like to help you publish a first version. Do you a have a list of things to be done before the first release?

**Comment by matthiaskrgr** [comment]
Hi, I started this as a "I'm trying to learn rust"-toy-project, but I *think* it's mostly done now, at least I'm out of ideas of what additional features to add (besides some nicer colored output / human readable and maybe machine readable (json?) output?
If you have any ideas, let me know!

I also need to decide a on a license and read up on the whole publishing to crates.io thing.

In the meantime, people can always install via git, maybe I should add a short paragraph to the readme.

**Comment by matthiaskrgr** [comment]
I pushed a release on crates.io and will close this issue. https://crates.io/crates/cargo-cache

Thanks for your patience!
