### ISSUE TITLE
"older-than" and "younger-than" are reversed

### ISSUE THREAD

**Issue by daboross** [matthiaskrgr/cargo-cache#80]
Hi,

Hope this is well received. When I read the documentation for cargo cache, it listed:

```
    -o, --remove-if-older-than <date>      Removes items older than specified date: YYYY.MM.DD or HH:MM:SS
```

I took this to mean that if I specified, say, `-o 2019.01.01`, it would remove all directories which were accessed (or created, i'm not sure) before 2019. However, through testing, I believe that cargo-cache implements the opposite!

When I run `cargo cache --remove-dir all --remove-if-older-than 1998.01.01 --dry-run`, I get a message:

```
dry-run: would delete 68369 items that are older than 1998.01.01...
```
Now, I don't mean to be suspicious, but I don't think there are many files on my computer created before it was.

On the other hand, running "younger than" with the same date gives many fewer files:
```
$ cargo cache --remove-dir all --remove-if-younger-than 1998.01.01 --dry-run
dry-run: would delete 16 items that are younger than 1998.01.01...
```
I'd expect this command to delete all of my files, as they should all have been created after 1998. But it only finds 16 (why are there 16 files that match this? I don't know).

In any case, either this is very confusingly worded, or these two parameters got accidentally switched somewhere.

Thanks!

**Comment by matthiaskrgr** [comment]
Urgh, yeah looks like I messed something up there, sorry about that. :(

This can probably be quick-fixed by simply swapping `<` and `>` [here](https://github.com/matthiaskrgr/cargo-cache/blob/master/src/date.rs#L98) and below that, but the fact that I messed this up probably means that I have to refactor the code to be a bit clearer (and add more tests...).. :/

I'm not very happy with the `--remove-if-{younger,older}-than` flag names, if you have any better ideas please let me know!

**Comment by daboross** [comment]
I can't really think of any _better_ options. I don't think there's any super good way to guard against logic errors like this besides extensive testing.

It isn't a perfect strategy, but capturing test coverage with something like [tarpaulin](https://github.com/xd009642/tarpaulin/) can be good? Even with 100% coverage it doesn't mean _every_ logical path is covered, but having 60-80% is going to be a marked improvement over 20-30%. I'm saying this with no knowledge of what testing you currently do in the crate, though, so take it with a grain of salt :)

**Comment by matthiaskrgr** [comment]
Sorry for the delay, was busy with some none-FOSS things.

I have pushed some minor refactoring and a fix for the bug.

Regarding tarpaulin, there are a lot of paths that are not really tested properly... :/
Perhaps I will add some tests that add files of different creation dates and so on and test with different `--remove-if..` parameters.

>Edit: looking at the code, maybe it'd be helpful to make DateComparison's variant names a bit less ambiguous?

Yeah I think that was definitely part of the problem :confused: . I hope the code is a bit less confusing now.


Anyway, thanks for the report, if you find further bugs or things that could be improved, please let me know!

I'll try to get a release out in the next few days.

**Comment by matthiaskrgr** [comment]
0.4.3 has been published.
