### ISSUE TITLE
sccache location logic doesn't work at least on macos

### ISSUE THREAD

**Issue by therealprof** [matthiaskrgr/cargo-cache#87]
Using `dirs` to get the general location does not work well at least on Mac (no idea about Windows, sorry). The reason is that usually vendors add their company name to the the directory added to the cache directory, also in this case (though the way Mozilla did that is super weird).

This
https://github.com/matthiaskrgr/cargo-cache/blob/21249c81ffcea87ecea48e0fd64d06a251a691ab/src/commands/sccache.rs#L44-L51

doesn't work because it expects the location to be in `~/Library/Caches/sccache`  while in reality it is in `~/Library/Caches/Mozilla.sccache`, cf. https://github.com/mozilla/sccache.

**Comment by matthiaskrgr** [comment]
Thanks, I don't have macos available unfortunately, can you please check if the `sccache_dir_macos_87` branch fixes this for you?

**Comment by therealprof** [comment]
Yes, that works. 👍

**Comment by matthiaskrgr** [comment]
Thanks for testing!

I'll try to get a new release out within the next 2-3 days!

**Comment by matthiaskrgr** [comment]
I published `0.5.1`.
