### ISSUE TITLE
clean-unref: Print statistics of removed files.

### ISSUE THREAD

**Issue by roblabla** [matthiaskrgr/cargo-cache#95]
Currently, while `cargo cache -a` will print a message indicating how much data it managed to clean up (`Size changed from 699.37 MB to 223.06 MB (-476.32 MB, -68.1%)`), `cargo cache clean-unref` will just silently exit without printing any sort of statistics.

Having `cargo cache clean-unref` print out those statistics would be very helpful to make sure things are working as intended.

**Comment by matthiaskrgr** [comment]
This is a good idea, thanks!

Should be implemented with  5e1385d  / in the master branch.

If you have any other ideas or suggestions, let me know! :)
