### ISSUE TITLE
clean-unref is removing crates that are specified in the lockfile

### ISSUE THREAD

**Issue by roblabla** [matthiaskrgr/cargo-cache#96]
It looks like clean-unref has a fairly big bug, because after building my repo (that has roughly 300 deps) and running `cargo clean-unref`, only a single dependency is left in my cargo registry cache:

```
$ cargo cache clean-unref
Size changed from 770.75 MB to 86.97 MB (-683.78 MB, -88.71%)
Cargo cache '/builds/hlab/isengard/agent-rust/.cargo_cache':
Total:                                  770.75 MB => 86.97 MB
  2 installed binaries:                              11.07 MB
  Registry:                             180.50 MB => 75.83 MB
    Registry index:                                  75.82 MB
    295 => 1 crate archives:              19.21 MB => 9.71 KB
    295 => 0 crate source checkouts:         85.47 MB => 0  B
  Git db:                               579.19 MB => 71.47 KB
    8 => 1 bare git repos:              155.39 MB => 71.47 KB
    8 => 0 git repo checkouts:              423.79 MB => 0  B
Size changed 770.75 MB => 86.97 MB (-683.78 MB, -88.71%)
```

I expect most of the 295 crate archives to stay around, as they are specified in the lockfile.

Quick reproducer:

```
# temporary cargo_home where the cache will be located
export CARGO_HOME=local_home
# Generate a crate with two dependencies, and build it to populate cache.
cargo new testing
cd testing
echo 'once_cell = "*"' >> Cargo.toml
echo 'lazy_static = "*"' >> Cargo.toml
cargo build
# Check that we have two cached crates.
ls local_home/registry/cache/github.com*
# This shouldn't delete any of the cached crate archives, as they're used by the build!
cargo cache clean-unref
# This will show a line like `2 => 1 crate archives`.
# That's bad! It deleted a crate that's needed to build!
# We can confirm one of our deps is missing in this ls.
ls local_home/registry/cache/github.com*
```

This issue seems to have appeared in cargo-cache 0.6.0. Version 0.5.1 did not remove required crates.

**Comment by matthiaskrgr** [comment]
Can reproduce.
I hoped this was just a cache-invalidation bug but on first glance it seems not.. :sweat_smile:

**Comment by matthiaskrgr** [comment]
I think the problem is that I use an iterator here https://github.com/matthiaskrgr/cargo-cache/blob/master/src/clean_unref.rs#L214
 and calling `.any()` does advance the iterator here https://github.com/matthiaskrgr/cargo-cache/blob/master/src/clean_unref.rs#L214 which causes problems when items are in random order

**Comment by matthiaskrgr** [comment]
@roblabla  can you confirm if this is fixed in the master branch? :)

**Comment by roblabla** [comment]
Yes, it seems to work! Thanks a lot for the quick fix <3

**Comment by matthiaskrgr** [comment]
Awesome, thanks!
Will push `0.6.1` in a bit.

The bug was probably present for 5 months now :smile:
