### ISSUE TITLE
--dry-run short flag should be -n, not -d

### ISSUE THREAD

**Issue by chris-morgan** [matthiaskrgr/cargo-cache#97]
cargo-cache is currently using `-d` as its short flag for `--dry-run`.

The standard short flag for `--dry-run` is `-n`. I confirmed this with a survey of man pages, `rg --context=2 --search-zip 'dry\\?-run' /usr/share/man`: the significant majority of programs accepting a `--dry-run` parameter support a short form, which is `-n` in all but one case. (The exception is `mktemp` using `-u`, probably because a dry run is <b>u</b>nsafe, though I confess myself confused as to why they even gave it a short form if it was so bad.)

This will be a breaking change, but should definitely be made.

**Comment by matthiaskrgr** [comment]
Thanks, I added a warning for `-d` now but it still works. I'll fully remove the old `-d` in a version or two I guess...
