### ISSUE TITLE
Document the syntax expected by `trim --limit`

### ISSUE THREAD

**Issue by ssokolow** [matthiaskrgr/cargo-cache#99]
I had to search the code to figure out what syntax `--limit` expects for the size value.

It needs to be documented... ideally in the `trim --help` output but, failing that, at least in the README.

**Comment by matthiaskrgr** [comment]
Right, the error message should definitely be improved. This also made me find another case where there is no error message at all where there should be one  :D 
(for example ``cargo-cache trim --limit  w`)

Also --dry-run did not work as expected :rofl: 

If you do something like `cargo-cache trim --dry-run --limit hello` you should now get an error message like
`Failed to parse limit: "hello". Should be of the form 123X where X is one of B,K,M,G or T.`

I also improved the --help output a bit.

**Comment by ssokolow** [comment]
Will do. Thanks for the quick response.
